# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

name: Felipe Gutierrez Barragan
email: fgutierrez3@wisc.edu
description: > # this means to ignore newlines until "url:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/

# Social
github_username: felipegb94 # put your github username
# twitter_username: # put your twitter username
linkedin_username: felipe-gutierrez-barragan-72686076  # put your linkedin username
# scholar_authorid: # put your google scholar author id
contact_note: >

# Footer text
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

# Blog
blog_name: fgb's blog
blog_description: research related posts, programming walkthroughs, tutorials

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  # poetry:
  #   output: true
  #   permalink: /poetry/:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# gems:
#   - 'jekyll/scholar'
# scholar:
# Raw

# Jekyll-Scholar
scholar:

  last_name: Gutierrez-Barragan

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib 
  # bibliography_template: "{{ reference | replace_first: 'Gutierrez, Felipe', '<b>Gutierrez, Felipe</b>' }}"

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other advanced settings (don't touch if you are not sure)
# -----------------------------------------------------------------------------
fontawesome_version: "4.6.3"
jquery_version: "1.12.4"
katex_version: "0.6.0"
